# <<<<<<<<<< exception hamdling >>>>>>>>>>
# try,except ,else , finally

# try:
#     name=input("enter your name:")
#     age=int(input("enter your age:"))
#     print("i am ",name,"and my age is",age) 
# except:
#     print("error is occured but don't worry , we will execute your remaining code ")
# else:
#     print("error is not occured")
# finally:
#     print("i will be always")
# print("i am important , pls execute me")    

# try:
#     num1=int(input("enter 1st number:"))
#     num2=int(input("enter 2nd number:"))
#     result=num1/num2
#     print(result)
# except ZeroDivisionError:
#     print("pls don't enter zero in 2nd number!") 
      
# except ValueError:
#     print("pls enter integer value !")    
  
# ls=[45,75,34,76,98,45,88,44,89,23]
# try:
#     target=int(input("enter your target item :"))
#     position=int(input("enter a position :"))
#     for i in range(len(ls)):
#         if target==ls[i]:
#             print("target is found")
#             print("position is :",i)
#             print(ls[position])
#         break
# except ValueError:
#     print(" pls enter integer value")
# except IndexError:
#     print("pls enter valid index")

# import sys
# try:
#      age=int(input("enter your age :"))
# except Exception as e:  # Exception is super clss
#     print(e)    

# ipynb ---> interactive notebook
#  jupyter notebook
#  ctrl + enter to execute the shell
   
    
        





